service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: godofjs
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: functions/auth.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
