service: serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: godofjs
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  register:
    handler: api/controllers/auth.registrationHandler
    events:
      - http: POST /api/v1/authentication/register
  login:
    handler: api/controllers/auth.loginHandler
    events:
      - http: POST /api/v1/authentication/login

